/// 职业技能库 —— 领域模型与数据（与 UI 原型 `MINDS` / `SKILLS` 一致）。
///
/// 九大门派各自拥有七本心法（`MINDS`），每本心法下有若干门绝技
/// （`SKILLS`，第 5 位为心法序号）。技能按 心法序号 分组展示。
library;

import 'package:flutter/foundation.dart';

/// 一本心法。
@immutable
class JobMind {
  const JobMind({required this.name, required this.desc});

  final String name;

  /// 心法一句话说明（如 吸纳内力，化为己用）。
  final String desc;
}

/// 一门技能。
@immutable
class JobSkill {
  const JobSkill({
    required this.name,
    required this.type,
    required this.cd,
    required this.desc,
    required this.mind,
  });

  /// 技能名（如 北冥神功）。
  final String name;

  /// 类型（主动 / 攻击 / 身法 …，决定 tag 配色）。
  final String type;

  /// 冷却（如 30s / —）。
  final String cd;

  /// 技能描述。
  final String desc;

  /// 所属心法序号（对应 `kJobMinds` 下标）。
  final int mind;
}

/// 九大门派心法（对应原型 `MINDS`；每派 7 本）。
const Map<String, List<JobMind>> kJobMinds = {
  'xiaoyao': [
    JobMind(name: '北冥神功', desc: '吸纳内力，化为己用'),
    JobMind(name: '小无相功', desc: '道家根基，模拟诸家'),
    JobMind(name: '凌波微步', desc: '步法如神，闪避无双'),
    JobMind(name: '八荒六合功', desc: '内劲外放，威慑八方'),
    JobMind(name: '逍遥御风', desc: '御风而行，轻功绝学'),
    JobMind(name: '传音搜魂', desc: '远程摄魂，点控定身'),
    JobMind(name: '五行奇门', desc: '奇门遁甲，布阵困敌'),
  ],
  'tianshan': [
    JobMind(name: '天山折梅手', desc: '三路锁拿，擒拿封穴'),
    JobMind(name: '天山六阳掌', desc: '阳劲掌法，刚猛沉雄'),
    JobMind(name: '生死符', desc: '冰晶暗器，生死由心'),
    JobMind(name: '白虹掌力', desc: '掌劲如虹，纵横无阻'),
    JobMind(name: '寒梅怒放', desc: '借力反击，暗藏杀机'),
    JobMind(name: '踏雪无痕', desc: '隐匿行踪，来去无踪'),
    JobMind(name: '冰蚕功', desc: '冰功入体，寒劲蚀髓'),
  ],
  'emei': [
    JobMind(name: '九阴真经', desc: '阴柔内功，爪劲凌厉'),
    JobMind(name: '清心普善咒', desc: '清心妙法，济世疗伤'),
    JobMind(name: '金顶绵掌', desc: '绵掌化劲，气脉悠长'),
    JobMind(name: '飘雪穿云掌', desc: '掌携霜雪，伤敌无形'),
    JobMind(name: '四象掌', desc: '四象轮转，攻守相济'),
    JobMind(name: '佛光普照', desc: '慈航普渡，护佑同门'),
    JobMind(name: '回风拂柳', desc: '身如拂柳，来去如风'),
  ],
  'shaolin': [
    JobMind(name: '易筋经', desc: '禅武合一，内壮根骨'),
    JobMind(name: '洗髓经', desc: '洗髓伐毛，外邪不侵'),
    JobMind(name: '大力金刚掌', desc: '刚猛掌力，金石为开'),
    JobMind(name: '拈花指', desc: '微笑拈花，点穴封印'),
    JobMind(name: '狮子吼', desc: '佛门狮吼，震慑群邪'),
    JobMind(name: '金刚伏魔圈', desc: '三渡合围，困魔降妖'),
    JobMind(name: '铁布衫', desc: '横练外功，金刚不坏'),
  ],
  'mingjiao': [
    JobMind(name: '圣火神功', desc: '圣火焚身，攻势不熄'),
    JobMind(name: '烈焰刀法', desc: '火刀燎原，灼伤敌人'),
    JobMind(name: '燃木刀法', desc: '枯木逢火，两段暴击'),
    JobMind(name: '葵花点穴手', desc: '摘叶飞花，封穴截脉'),
    JobMind(name: '乾坤大挪移', desc: '借力打力，转移乾坤'),
    JobMind(name: '光明圣火阵', desc: '圣火护体，鼓舞同门'),
    JobMind(name: '九阳神功', desc: '九阳护体，生生不息'),
  ],
  'gaibang': [
    JobMind(name: '降龙十八掌', desc: '天下第一刚猛掌法'),
    JobMind(name: '打狗棒法', desc: '帮主绝学，棒法灵动'),
    JobMind(name: '太祖长拳', desc: '拳出有据，大巧不工'),
    JobMind(name: '疯魔杖法', desc: '杖势疯魔，越战越勇'),
    JobMind(name: '锁喉擒拿功', desc: '擒龙锁喉，近身制敌'),
    JobMind(name: '莲花掌', desc: '掌开莲花，绵里藏针'),
    JobMind(name: '排云双掌', desc: '排云见日，双掌开碑'),
  ],
  'wudang': [
    JobMind(name: '纯阳无极功', desc: '纯阳内功，绵长浑厚'),
    JobMind(name: '太极拳', desc: '以柔克刚，化劲卸力'),
    JobMind(name: '太极剑意', desc: '剑意圆转，攻守一体'),
    JobMind(name: '神门十三剑', desc: '剑指神门，封招断势'),
    JobMind(name: '梯云纵', desc: '轻身提纵，飘忽如仙'),
    JobMind(name: '真武七截阵', desc: '真武临阵，全队增攻'),
    JobMind(name: '武当九阳功', desc: '内息流转，护体生罡'),
  ],
  'xingxiu': [
    JobMind(name: '化功大法', desc: '化去内力，废人武功'),
    JobMind(name: '星宿毒经', desc: '诸毒总纲，百毒俱备'),
    JobMind(name: '抽髓掌', desc: '阴毒掌力，蚀骨吸髓'),
    JobMind(name: '三阴蜈蚣爪', desc: '毒爪撕裂，行动迟缓'),
    JobMind(name: '含笑半步颠', desc: '奇毒无形，寸步难行'),
    JobMind(name: '神木王鼎', desc: '御蛊驱毒，全队增毒'),
    JobMind(name: '龟息功', desc: '龟息假死，金蝉脱壳'),
  ],
  'murong': [
    JobMind(name: '斗转星移', desc: '转移伤害，还施彼身'),
    JobMind(name: '参合指', desc: '指力凌厉，隔空伤敌'),
    JobMind(name: '家传剑法', desc: '世家剑法，连环三刺'),
    JobMind(name: '还施水阁', desc: '演武阁中，博采众长'),
    JobMind(name: '镜花水月', desc: '身形如幻，虚实难辨'),
    JobMind(name: '以彼之道', desc: '模拟敌招，反制其人'),
    JobMind(name: '燕坞心诀', desc: '慕容心法，内外兼修'),
  ],
};

/// 九大门派技能（对应原型 `SKILLS`）。
const Map<String, List<JobSkill>> kJobSkills = {
  'xiaoyao': [
    JobSkill(
      name: '北冥神功',
      type: '主动',
      cd: '30s',
      desc: '吸取目标内力并造成内功伤害',
      mind: 0,
    ),
    JobSkill(name: '溪山行旅', type: '攻击', cd: '12s', desc: '对目标造成高额内功伤害', mind: 1),
    JobSkill(
      name: '弹指神通',
      type: '攻击',
      cd: '8s',
      desc: '远程点穴，造成伤害并打断吟唱',
      mind: 1,
    ),
    JobSkill(
      name: '无相劫指',
      type: '攻击',
      cd: '18s',
      desc: '指力无形，穿透内防造成内功伤害',
      mind: 1,
    ),
    JobSkill(
      name: '凌波微步',
      type: '身法',
      cd: '60s',
      desc: '短时间内大幅提升闪避，免疫减速效果',
      mind: 2,
    ),
    JobSkill(
      name: '寒袖拂穴',
      type: '控制',
      cd: '40s',
      desc: '袖风拂穴，使目标沉默数秒',
      mind: 2,
    ),
    JobSkill(
      name: '八荒六合',
      type: '增益',
      cd: '120s',
      desc: '内劲外放，短时大幅提升自身内功攻击与命中',
      mind: 3,
    ),
    JobSkill(
      name: '御风行',
      type: '身法',
      cd: '45s',
      desc: '身轻如燕，移速大增并解除自身减速',
      mind: 4,
    ),
    JobSkill(name: '云体风身', type: '被动', cd: '—', desc: '永久提升自身会心与身法', mind: 4),
    JobSkill(
      name: '画地为牢',
      type: '控制',
      cd: '60s',
      desc: '摄魂定身，定身目标数秒，受到攻击解除',
      mind: 5,
    ),
    JobSkill(
      name: '八阵图',
      type: '陷阱',
      cd: '45s',
      desc: '布下奇门阵法，触发后禁锢范围内敌人',
      mind: 6,
    ),
    JobSkill(
      name: '奇门遁甲',
      type: '增益',
      cd: '90s',
      desc: '布下奇门，提升全队闪避与会心抵抗',
      mind: 6,
    ),
  ],
  'tianshan': [
    JobSkill(
      name: '兰花点穴手',
      type: '控制',
      cd: '45s',
      desc: '封穴目标，使其无法行动',
      mind: 0,
    ),
    JobSkill(
      name: '折梅锁喉',
      type: '攻击',
      cd: '20s',
      desc: '锁拿咽喉，造成伤害并降低目标命中',
      mind: 0,
    ),
    JobSkill(
      name: '凤舞九天',
      type: '攻击',
      cd: '15s',
      desc: '跃起俯冲，对目标造成外功伤害并减速',
      mind: 1,
    ),
    JobSkill(
      name: '阳歌天钧',
      type: '攻击',
      cd: '25s',
      desc: '掌挟阳劲，击退目标并附加内伤',
      mind: 1,
    ),
    JobSkill(
      name: '生死符',
      type: '控制',
      cd: '50s',
      desc: '冰晶入体，持续冻伤并大幅减速',
      mind: 2,
    ),
    JobSkill(
      name: '金蝉脱壳',
      type: '解控',
      cd: '120s',
      desc: '解除所有控制效果并短暂隐身',
      mind: 2,
    ),
    JobSkill(name: '鹰击长空', type: '攻击', cd: '20s', desc: '瞬移至目标身后发动突袭', mind: 3),
    JobSkill(
      name: '白虹贯日',
      type: '攻击',
      cd: '14s',
      desc: '贯日一击，无视目标部分外防',
      mind: 3,
    ),
    JobSkill(
      name: '移花接木',
      type: '增益',
      cd: '90s',
      desc: '将受到的部分伤害反弹给攻击者',
      mind: 4,
    ),
    JobSkill(
      name: '寒梅怒放',
      type: '攻击',
      cd: '30s',
      desc: '受击触发怒放，对周围敌人反震冰劲',
      mind: 4,
    ),
    JobSkill(
      name: '踏雪无痕',
      type: '身法',
      cd: '60s',
      desc: '进入隐身状态，移动速度提升',
      mind: 5,
    ),
    JobSkill(name: '冰肌玉骨', type: '被动', cd: '—', desc: '永久提升冰属性攻击与会心', mind: 6),
  ],
  'emei': [
    JobSkill(
      name: '九阴神爪',
      type: '攻击',
      cd: '18s',
      desc: '抓取目标，持续造成内功伤害',
      mind: 0,
    ),
    JobSkill(
      name: '摧心掌',
      type: '攻击',
      cd: '16s',
      desc: '掌劲透体，附加内伤并降低目标内防',
      mind: 0,
    ),
    JobSkill(
      name: '清心普善咒',
      type: '治疗',
      cd: '5s',
      desc: '为友方单体恢复大量生命值',
      mind: 1,
    ),
    JobSkill(
      name: '起死回生',
      type: '复活',
      cd: '120s',
      desc: '复活倒地队友，并恢复其部分气血',
      mind: 1,
    ),
    JobSkill(name: '金顶绵掌', type: '被动', cd: '—', desc: '永久提升治疗量与气上限', mind: 2),
    JobSkill(
      name: '佛心护体',
      type: '增益',
      cd: '90s',
      desc: '为队友施加护体佛光，吸收部分伤害',
      mind: 2,
    ),
    JobSkill(
      name: '西子捧心',
      type: '攻击',
      cd: '15s',
      desc: '对目标造成内功伤害并附加减速',
      mind: 3,
    ),
    JobSkill(
      name: '飘雪穿云',
      type: '攻击',
      cd: '22s',
      desc: '掌风如雪，减速范围内敌人',
      mind: 3,
    ),
    JobSkill(name: '月落西山', type: '控制', cd: '60s', desc: '使范围内敌人陷入昏睡', mind: 4),
    JobSkill(
      name: '四象合围',
      type: '攻击',
      cd: '28s',
      desc: '四象掌影合围，命中目标越多伤害越高',
      mind: 4,
    ),
    JobSkill(name: '佛光普照', type: '治疗', cd: '30s', desc: '治疗自身周围的所有队友', mind: 5),
    JobSkill(
      name: '呆若木鸡',
      type: '保命',
      cd: '300s',
      desc: '免疫所有伤害，但无法行动',
      mind: 5,
    ),
    JobSkill(
      name: '回风拂柳',
      type: '身法',
      cd: '45s',
      desc: '身形飘忽，提升自身闪避与移动速度',
      mind: 6,
    ),
  ],
  'shaolin': [
    JobSkill(name: '易筋经', type: '被动', cd: '—', desc: '永久提升体力与受到的治疗效果', mind: 0),
    JobSkill(
      name: '礼敬如来',
      type: '治疗',
      cd: '60s',
      desc: '为自身恢复气血，并提升外防',
      mind: 0,
    ),
    JobSkill(
      name: '袈裟伏魔功',
      type: '攻击',
      cd: '20s',
      desc: '掷出袈裟缠绕目标，造成持续伤害',
      mind: 1,
    ),
    JobSkill(
      name: '佛法无边',
      type: '增益',
      cd: '90s',
      desc: '诵经结印，提升周围队友外功防御',
      mind: 1,
    ),
    JobSkill(
      name: '大力金刚掌',
      type: '攻击',
      cd: '12s',
      desc: '蓄力一击，对目标造成高额外功伤害',
      mind: 2,
    ),
    JobSkill(
      name: '韦陀杵',
      type: '攻击',
      cd: '16s',
      desc: '杵随身走，对流血目标伤害提升',
      mind: 2,
    ),
    JobSkill(
      name: '拈花指',
      type: '控制',
      cd: '30s',
      desc: '点穴封印目标，使其无法行动',
      mind: 3,
    ),
    JobSkill(name: '一苇渡江', type: '身法', cd: '40s', desc: '踏苇而行，瞬身贴近目标', mind: 3),
    JobSkill(name: '狮子吼', type: '控制', cd: '40s', desc: '震慑周围敌人，附加减速', mind: 4),
    JobSkill(
      name: '伏魔杖法',
      type: '攻击',
      cd: '18s',
      desc: '杖影如山，对周围敌人造成外功伤害',
      mind: 4,
    ),
    JobSkill(
      name: '金刚伏魔圈',
      type: '控制',
      cd: '45s',
      desc: '布下伏魔阵，禁锢范围内敌人并持续伤害',
      mind: 5,
    ),
    JobSkill(name: '铁布衫', type: '增益', cd: '90s', desc: '大幅提升自身外防与体力', mind: 6),
    JobSkill(
      name: '金钟罩',
      type: '保命',
      cd: '240s',
      desc: '金钟罩体，短时免疫外功伤害',
      mind: 6,
    ),
  ],
  'mingjiao': [
    JobSkill(name: '圣火令法', type: '被动', cd: '—', desc: '永久提升火属性攻击与命中', mind: 0),
    JobSkill(
      name: '圣火燎原',
      type: '攻击',
      cd: '25s',
      desc: '腾身而起，对目标区域落下火雨',
      mind: 0,
    ),
    JobSkill(
      name: '烈焰刀',
      type: '攻击',
      cd: '10s',
      desc: '附着圣火劲力，造成外伤并附加灼烧',
      mind: 1,
    ),
    JobSkill(
      name: '焚天烈焰',
      type: '攻击',
      cd: '20s',
      desc: '烈焰缠身，持续灼烧周围敌人',
      mind: 1,
    ),
    JobSkill(
      name: '燃木刀法',
      type: '攻击',
      cd: '15s',
      desc: '连续两段劈砍，第二段必定暴击',
      mind: 2,
    ),
    JobSkill(
      name: '燎原百击',
      type: '攻击',
      cd: '18s',
      desc: '连环快刀，每一击伤害递增',
      mind: 2,
    ),
    JobSkill(name: '葵花点穴手', type: '控制', cd: '35s', desc: '点中要穴，封穴数秒', mind: 3),
    JobSkill(
      name: '封穴截脉',
      type: '控制',
      cd: '50s',
      desc: '截脉封穴，禁用目标轻功数秒',
      mind: 3,
    ),
    JobSkill(
      name: '乾坤大挪移',
      type: '增益',
      cd: '120s',
      desc: '借力打力，短时间反弹受到的伤害',
      mind: 4,
    ),
    JobSkill(
      name: '移形换位',
      type: '身法',
      cd: '60s',
      desc: '与队友瞬间换位，解除自身控制',
      mind: 4,
    ),
    JobSkill(
      name: '光明圣火阵',
      type: '增益',
      cd: '90s',
      desc: '布下圣火阵，提升周围队友外功攻击',
      mind: 5,
    ),
    JobSkill(name: '九阳神功', type: '被动', cd: '—', desc: '永久提升气血上限与内力回复', mind: 6),
  ],
  'gaibang': [
    JobSkill(
      name: '亢龙有悔',
      type: '攻击',
      cd: '14s',
      desc: '刚猛一掌，对目标造成大量外功伤害',
      mind: 0,
    ),
    JobSkill(name: '飞龙在天', type: '攻击', cd: '20s', desc: '跃起俯击，击退周围敌人', mind: 0),
    JobSkill(
      name: '降龙十八掌',
      type: '攻击',
      cd: '90s',
      desc: '终极掌法，消耗全部怒气造成毁灭性伤害',
      mind: 0,
    ),
    JobSkill(
      name: '棒打狗头',
      type: '控制',
      cd: '30s',
      desc: '打狗棒法精髓，眩晕目标两秒',
      mind: 1,
    ),
    JobSkill(
      name: '天下无狗',
      type: '攻击',
      cd: '45s',
      desc: '棒影漫天，对周围敌人连续打击',
      mind: 1,
    ),
    JobSkill(name: '打狗棒法', type: '被动', cd: '—', desc: '永久提升身法与技能触发概率', mind: 1),
    JobSkill(
      name: '太祖长拳',
      type: '攻击',
      cd: '10s',
      desc: '拳法质朴，命中后提升自身命中',
      mind: 2,
    ),
    JobSkill(
      name: '猛虎出林',
      type: '攻击',
      cd: '16s',
      desc: '向前扑击，命中后回复怒气',
      mind: 2,
    ),
    JobSkill(
      name: '疯魔杖法',
      type: '攻击',
      cd: '22s',
      desc: '杖势渐猛，自身气血越低伤害越高',
      mind: 3,
    ),
    JobSkill(
      name: '擒龙功',
      type: '控制',
      cd: '40s',
      desc: '隔空擒拿，将远处目标拉至身前',
      mind: 4,
    ),
    JobSkill(
      name: '莲花掌',
      type: '攻击',
      cd: '15s',
      desc: '掌影如莲，附加持续流血效果',
      mind: 5,
    ),
    JobSkill(
      name: '排云双掌',
      type: '攻击',
      cd: '28s',
      desc: '双掌齐出，击退目标并附加减速',
      mind: 6,
    ),
  ],
  'wudang': [
    JobSkill(name: '纯阳无极功', type: '被动', cd: '—', desc: '永久提升内功攻击与会心', mind: 0),
    JobSkill(
      name: '三环套月',
      type: '攻击',
      cd: '14s',
      desc: '剑光三叠，第三段附带破防效果',
      mind: 0,
    ),
    JobSkill(name: '太极拳', type: '被动', cd: '—', desc: '受击时有概率化解部分伤害', mind: 1),
    JobSkill(
      name: '揽雀尾',
      type: '攻击',
      cd: '16s',
      desc: '沾连粘随，反弹目标的部分伤害',
      mind: 1,
    ),
    JobSkill(
      name: '太极剑意',
      type: '解控',
      cd: '90s',
      desc: '以意驭剑，解除控制并短暂免疫控制',
      mind: 2,
    ),
    JobSkill(
      name: '白鹤亮翅',
      type: '攻击',
      cd: '12s',
      desc: '剑走轻灵，对目标造成内功伤害',
      mind: 2,
    ),
    JobSkill(
      name: '天马飞瀑',
      type: '攻击',
      cd: '16s',
      desc: '剑气如瀑，对范围内敌人造成伤害',
      mind: 2,
    ),
    JobSkill(name: '仙人指路', type: '控制', cd: '35s', desc: '剑指点穴，使目标沉默', mind: 3),
    JobSkill(
      name: '神门十三剑',
      type: '攻击',
      cd: '24s',
      desc: '连点十三剑，命中后封禁目标技能数秒',
      mind: 3,
    ),
    JobSkill(
      name: '梯云纵',
      type: '身法',
      cd: '60s',
      desc: '轻身提纵，大幅提升闪避与移动速度',
      mind: 4,
    ),
    JobSkill(
      name: '真武七截阵',
      type: '增益',
      cd: '120s',
      desc: '布下真武阵法，提升全队内功攻击',
      mind: 5,
    ),
    JobSkill(
      name: '武当九阳功',
      type: '增益',
      cd: '100s',
      desc: '罡气护体，为全队附加吸收伤害的护盾',
      mind: 6,
    ),
  ],
  'xingxiu': [
    JobSkill(
      name: '化功大法',
      type: '攻击',
      cd: '20s',
      desc: '化去目标内力，并使其内功受损',
      mind: 0,
    ),
    JobSkill(
      name: '吸功入体',
      type: '攻击',
      cd: '30s',
      desc: '化目标内力为己用，恢复自身内力',
      mind: 0,
    ),
    JobSkill(
      name: '连珠腐尸毒',
      type: '攻击',
      cd: '15s',
      desc: '释放毒瘴，范围内敌人持续中毒',
      mind: 1,
    ),
    JobSkill(
      name: '万毒噬心',
      type: '攻击',
      cd: '26s',
      desc: '毒气攻心，中毒目标受到的伤害递增',
      mind: 1,
    ),
    JobSkill(
      name: '抽髓掌',
      type: '攻击',
      cd: '10s',
      desc: '阴毒掌力，命中后附加中毒效果',
      mind: 2,
    ),
    JobSkill(
      name: '三阴蜈蚣爪',
      type: '控制',
      cd: '35s',
      desc: '爪毒入体，使目标行动迟缓',
      mind: 3,
    ),
    JobSkill(
      name: '含笑半步颠',
      type: '控制',
      cd: '60s',
      desc: '奇毒无形，目标每移动一步皆受毒伤',
      mind: 4,
    ),
    JobSkill(
      name: '见血封喉',
      type: '控制',
      cd: '45s',
      desc: '剧毒入血，使目标沉默数秒',
      mind: 4,
    ),
    JobSkill(
      name: '神木王鼎',
      type: '增益',
      cd: '90s',
      desc: '祭出王鼎，提升周围队友毒属性攻击',
      mind: 5,
    ),
    JobSkill(
      name: '御蛊术',
      type: '增益',
      cd: '80s',
      desc: '祭出毒蛊，反噬攻击自己的敌人',
      mind: 5,
    ),
    JobSkill(
      name: '龟息功',
      type: '保命',
      cd: '180s',
      desc: '假死龟息，期间免疫所有伤害',
      mind: 6,
    ),
  ],
  'murong': [
    JobSkill(
      name: '斗转星移',
      type: '增益',
      cd: '90s',
      desc: '转移自身所受伤害，反弹给攻击者',
      mind: 0,
    ),
    JobSkill(name: '星移斗转', type: '被动', cd: '—', desc: '永久提升内外功与气血上限', mind: 0),
    JobSkill(
      name: '参合指',
      type: '攻击',
      cd: '12s',
      desc: '隔空一指，造成内功伤害并打断吟唱',
      mind: 1,
    ),
    JobSkill(
      name: '指惊四座',
      type: '攻击',
      cd: '20s',
      desc: '指风四射，命中后降低目标内防',
      mind: 1,
    ),
    JobSkill(
      name: '家传剑法',
      type: '攻击',
      cd: '15s',
      desc: '慕容世家剑招，对目标连续刺击三次',
      mind: 2,
    ),
    JobSkill(
      name: '剑气纵横',
      type: '攻击',
      cd: '24s',
      desc: '剑气外放，贯穿直线上的敌人',
      mind: 2,
    ),
    JobSkill(
      name: '还施水阁',
      type: '被动',
      cd: '—',
      desc: '牢记所受招式，永久提升自身命中',
      mind: 3,
    ),
    JobSkill(
      name: '听香行',
      type: '身法',
      cd: '50s',
      desc: '水榭听香，快速位移至队友身边',
      mind: 3,
    ),
    JobSkill(
      name: '镜花水月',
      type: '身法',
      cd: '60s',
      desc: '身形如幻，短时间内闪避大幅提升',
      mind: 4,
    ),
    JobSkill(
      name: '以彼之道',
      type: '控制',
      cd: '45s',
      desc: '模仿目标招式反制，封印其技能',
      mind: 5,
    ),
    JobSkill(
      name: '以其人之道',
      type: '攻击',
      cd: '30s',
      desc: '模仿目标最近使用的技能，反施其身',
      mind: 5,
    ),
    JobSkill(
      name: '燕坞心诀',
      type: '被动',
      cd: '—',
      desc: '慕容内功心法，永久提升会心与内力上限',
      mind: 6,
    ),
  ],
};
